PGPassword=""
JWTSecret=""
S3AccessKey=""
S3SecretKey=""
S3Host=""
S3Secure=""
SlackWebhook=""
LogRequests=""
DiscordToken=""
DiscordPublicPostChannel=""
DiscordLinkBookmarkChannel=""
TimelapseWorkers=""
TimelapseWorkerAccessKey=""
AddCORS=""
