version: '3.1'

networks:
  back-tier:

services:

  redis:
    image: redis
    volumes:
      - ./redis:/data
    restart: always
    networks:
      - back-tier

  postgres:
    image: postgres
    shm_size: 1g
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    networks:
      - back-tier
