FROM golang:1.13.3

RUN apt-get update && \
    apt-get install -y imagemagick && \
    apt-get install -y libmagickwand-dev && \
    apt-get install -y ffmpeg

RUN go get -u github.com/cosmtrek/air

RUN mkdir /app
WORKDIR /app

EXPOSE 8083

ENTRYPOINT ["/go/bin/air", "-c", ".air.timelapse.conf"]
