FROM debian

RUN apt-get update && \
    apt-get install -y imagemagick && \
    apt-get install -y libmagickwand-dev && \
    apt-get install -y ffmpeg
COPY assets /usr/local/share/appbackend

COPY ca-certificates.crt /etc/ssl/certs/
COPY bin/timelapse /
COPY db /db

EXPOSE 8083

ENTRYPOINT ["/timelapse"]
